### ISSUE TITLE
Fine Tuning Radiation Model

### ISSUE THREAD

**Issue by pabloconrat** [pabloconrat/our_first_climate_model#27]
My version of the radiation model isn't producing the exact values of the benchmarks.

**Comment by TBardachova** [comment]
Hi :) I didn't run your code and I did'n see your values, but from quick look on your code I think it can be because of test T values you use. If you remember we had this mistake at the beginning, we should calculate the T values for every layer from T for every level first. At least it works in my code with such T values:

for (int i=0; i<Consts::nlayer; i++) {
    T[i] = (Tlevel[i] + Tlevel[i+1])/2.0; // T-profile for each layer
  }

@pabloconrat

**Comment by pabloconrat** [comment]
Hi, thanks for the feedback. I will try that! So far I used the first entry in the example vector as the surface temperature but I still can interpolate for the rest (aka the layer temperatures). Good point!

**Comment by pabloconrat** [comment]
I just adapted it and it looks much better. There is some sort of index error in the E_up left. Otherwise looking good 🥳

**Comment by TBardachova** [comment]
I also had a look on the code now and find one little mistake in L_down computation:
L_down = (1 - alpha(tau[ilev - 1], mu[imu])) * L_down + alpha(tau[ilev - 1], mu[imu]) * cplkavg(Consts::lamdas[i_rad], Consts::lamdas[i_rad+1], **T[ilev - 1]**);
Also I defined L_up near surface like this:
double L_up = cplkavg(Consts::lamdas[i_rad], Consts::lamdas[i_rad+1], **Consts::T0**);
where Consts::T0 = 288.0. As I remember Felix said us on the class last week that T_surface should be equal to that value if we want get banckmarks values.
With this changes I got same values as at banckmark, so seems we done with this task :) 
I uploaded my vesion to my branch, so feel free to look on it and maybe you will have some remarks :)

**Comment by TBardachova** [comment]
Also I forgot to notice that I also changed the loop for E_up:
 for (int ilev=**Consts::nlevel-2**; ilev >= 0; --ilev)
because we already calculate E_up for lowest level in this step:
E_up[E_up.size()] += 2 * M_PI * L_up * mu[imu] * dmu;

Probably it is all. I also made some changes in variables definition and deleted part of code which we don't use, just for my better understanding the structure, but it have no influence on computations results :)

**Comment by pabloconrat** [comment]
Great! I just copied your changes and it works! Will work on window atmosphere tomorross or on saturday
